import { applyProjectProgress } from "@/lib/progress";
import type { Project, Task } from "@/types";

const now = "2026-04-02T09:00:00.000Z";

const baseProjects: Project[] = [
  {
    id: "project-2026-plan",
    name: "2026 사업계획",
    description: "2026년 핵심 실행 과제를 계층형으로 관리하는 메인 프로그램입니다.",
    parentId: null,
    depth: 1,
    progress: 0,
    color: "blue",
    status: "active",
    isFavorite: true,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-pmo",
    ownerId: "user-admin",
    createdById: "user-admin",
    updatedById: "user-admin",
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-product-dev",
    name: "제품개발",
    description: "제품 경쟁력과 운영 효율을 끌어올리는 개발 트랙입니다.",
    parentId: "project-2026-plan",
    depth: 2,
    progress: 0,
    color: "violet",
    status: "active",
    isFavorite: true,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-product",
    ownerId: "user-manager-product",
    createdById: "user-admin",
    updatedById: "user-manager-product",
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-simulator",
    name: "의료 시뮬레이터 고도화",
    description: "콘텐츠 확장, UX 개선, 성능 최적화를 동시에 진행합니다.",
    parentId: "project-product-dev",
    depth: 3,
    progress: 0,
    color: "rose",
    status: "active",
    isFavorite: false,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-product",
    ownerId: "user-manager-product",
    createdById: "user-manager-product",
    updatedById: "user-manager-product",
    approval: {
      status: "approved",
      approverId: "user-manager-product",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-cost-structure",
    name: "원가 구조 개선",
    description: "BOM 재정비와 공급사 협상으로 수익성을 개선합니다.",
    parentId: "project-product-dev",
    depth: 3,
    progress: 0,
    color: "amber",
    status: "active",
    isFavorite: false,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-product",
    ownerId: "user-manager-product",
    createdById: "user-manager-product",
    updatedById: "user-manager-product",
    approval: {
      status: "approved",
      approverId: "user-manager-product",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-sales-marketing",
    name: "영업/마케팅",
    description: "시장 진입과 리드 전환 성과를 높이는 영업·마케팅 트랙입니다.",
    parentId: "project-2026-plan",
    depth: 2,
    progress: 0,
    color: "emerald",
    status: "active",
    isFavorite: false,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-sales",
    ownerId: "user-manager-sales",
    createdById: "user-admin",
    updatedById: "user-manager-sales",
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-exhibition",
    name: "해외 전시회 준비",
    description: "글로벌 전시회 참가 준비와 후속 리드 운영을 관리합니다.",
    parentId: "project-sales-marketing",
    depth: 3,
    progress: 0,
    color: "cyan",
    status: "active",
    isFavorite: false,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-sales",
    ownerId: "user-manager-sales",
    createdById: "user-manager-sales",
    updatedById: "user-manager-sales",
    approval: {
      status: "approved",
      approverId: "user-manager-sales",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-management-support",
    name: "경영지원",
    description: "내부 운영 안정화와 지원 체계 개선 과제를 관리합니다.",
    parentId: "project-2026-plan",
    depth: 2,
    progress: 0,
    color: "slate",
    status: "active",
    isFavorite: false,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-support",
    ownerId: "user-admin",
    createdById: "user-admin",
    updatedById: "user-admin",
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-erp",
    name: "ERP 운영 안정화",
    description: "ERP 운영 리스크를 줄이고 지원 프로세스를 정비합니다.",
    parentId: "project-management-support",
    depth: 3,
    progress: 0,
    color: "blue",
    status: "internal_review",
    isFavorite: false,
    isArchived: false,
    archivedAt: null,
    departmentId: "dept-support",
    ownerId: "user-member-2",
    createdById: "user-admin",
    updatedById: "user-member-2",
    approval: {
      status: "pending",
      approverId: "user-admin",
      approvedAt: null,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project-legacy",
    name: "2025 전환 과제",
    description: "완료된 과제를 보관하는 아카이브 예시 프로젝트입니다.",
    parentId: null,
    depth: 1,
    progress: 100,
    color: "slate",
    status: "done",
    isFavorite: false,
    isArchived: true,
    archivedAt: now,
    departmentId: "dept-pmo",
    ownerId: "user-admin",
    createdById: "user-admin",
    updatedById: "user-admin",
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  },
];

const baseTasks: Task[] = [
  {
    id: "task-simulator-ux",
    projectId: "project-simulator",
    parentTaskId: null,
    title: "시뮬레이터 UX 리뉴얼 범위 확정",
    description: "의사 및 간호사 그룹 인터뷰를 바탕으로 리뉴얼 범위를 확정합니다.",
    assignee: "김민지",
    assigneeId: "user-manager-product",
    priority: "high",
    status: "in_progress",
    isCompleted: false,
    startDate: "2026-04-01",
    dueDate: "2026-04-05",
    memo: "4월 첫째 주 사용자 리뷰 세션 예정",
    checklist: [
      { id: "check-ux-1", text: "인터뷰 결과 정리", isCompleted: true, createdAt: now },
      { id: "check-ux-2", text: "핵심 화면 우선순위 정의", isCompleted: false, createdAt: now },
    ],
    approval: {
      status: "not_required",
      approverId: null,
      approvedAt: null,
    },
    createdById: "user-manager-product",
    updatedById: "user-manager-product",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-simulator-ux-sub",
    projectId: "project-simulator",
    parentTaskId: "task-simulator-ux",
    title: "리뉴얼 화면 와이어프레임 작성",
    description: "메인 흐름 중심으로 1차 와이어프레임을 작성합니다.",
    assignee: "이수빈",
    assigneeId: null,
    priority: "medium",
    status: "planned",
    isCompleted: false,
    startDate: "2026-04-02",
    dueDate: "2026-04-04",
    memo: "",
    checklist: [],
    approval: {
      status: "not_required",
      approverId: null,
      approvedAt: null,
    },
    createdById: "user-manager-product",
    updatedById: "user-manager-product",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-simulator-content",
    projectId: "project-simulator",
    parentTaskId: null,
    title: "신규 교육 시나리오 3종 시작",
    description: "응급처치, 감염관리, 투약 시뮬레이션 시나리오를 시작합니다.",
    assignee: "박주연",
    assigneeId: "user-member-1",
    priority: "urgent",
    status: "approval_pending",
    isCompleted: false,
    startDate: "2026-03-29",
    dueDate: "2026-04-03",
    memo: "의학 자문 검수 대기",
    checklist: [],
    approval: {
      status: "pending",
      approverId: "user-manager-product",
      approvedAt: null,
    },
    createdById: "user-member-1",
    updatedById: "user-member-1",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-cost-vendor",
    projectId: "project-cost-structure",
    parentTaskId: null,
    title: "핵심 부품 단가 협상",
    description: "상위 5개 원가 항목 공급사와 2차 협상을 진행합니다.",
    assignee: "정서윤",
    assigneeId: null,
    priority: "high",
    status: "planned",
    isCompleted: false,
    startDate: "2026-04-04",
    dueDate: "2026-04-10",
    memo: "재무팀 검토 자료 필요",
    checklist: [
      { id: "check-vendor-1", text: "원가 비교표 업데이트", isCompleted: false, createdAt: now },
    ],
    approval: {
      status: "not_required",
      approverId: null,
      approvedAt: null,
    },
    createdById: "user-manager-product",
    updatedById: "user-manager-product",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-cost-bom",
    projectId: "project-cost-structure",
    parentTaskId: null,
    title: "BOM 구조 재정비",
    description: "제품군별 원가 구조를 재정의하고 표준 템플릿을 정리합니다.",
    assignee: "이도현",
    assigneeId: null,
    priority: "medium",
    status: "done",
    isCompleted: true,
    startDate: "2026-03-20",
    dueDate: "2026-03-31",
    memo: "1차 원가 기준표 배포 완료",
    checklist: [
      { id: "check-bom-1", text: "표준 BOM 항목 정리", isCompleted: true, createdAt: now },
      { id: "check-bom-2", text: "양식 배포", isCompleted: true, createdAt: now },
    ],
    approval: {
      status: "approved",
      approverId: "user-manager-product",
      approvedAt: now,
    },
    createdById: "user-manager-product",
    updatedById: "user-manager-product",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-exhibition-booth",
    projectId: "project-exhibition",
    parentTaskId: null,
    title: "전시 부스 시안 확정",
    description: "브랜드 메시지와 제품 데모 동선을 반영한 부스 시안을 확정합니다.",
    assignee: "최유진",
    assigneeId: "user-manager-sales",
    priority: "urgent",
    status: "in_progress",
    isCompleted: false,
    startDate: "2026-04-01",
    dueDate: "2026-04-04",
    memo: "현지 파트너와 시공 협의 필요",
    checklist: [],
    approval: {
      status: "not_required",
      approverId: null,
      approvedAt: null,
    },
    createdById: "user-manager-sales",
    updatedById: "user-manager-sales",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-exhibition-leads",
    projectId: "project-exhibition",
    parentTaskId: null,
    title: "현장 리드 수집 프로세스 정리",
    description: "QR 기반 리드 수집과 CRM 연동 프로세스를 정리합니다.",
    assignee: "서지훈",
    assigneeId: null,
    priority: "medium",
    status: "planned",
    isCompleted: false,
    startDate: "2026-04-06",
    dueDate: "2026-04-12",
    memo: "마케팅 자동화 연동 검토",
    checklist: [],
    approval: {
      status: "not_required",
      approverId: null,
      approvedAt: null,
    },
    createdById: "user-manager-sales",
    updatedById: "user-manager-sales",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-erp-monitoring",
    projectId: "project-erp",
    parentTaskId: null,
    title: "운영 모니터링 대시보드 정비",
    description: "ERP 배치와 API 모니터링 지표를 재정리합니다.",
    assignee: "한세진",
    assigneeId: null,
    priority: "high",
    status: "done",
    isCompleted: true,
    startDate: "2026-03-18",
    dueDate: "2026-03-27",
    memo: "알림 기준값 재설정 완료",
    checklist: [],
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdById: "user-admin",
    updatedById: "user-member-2",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-erp-runbook",
    projectId: "project-erp",
    parentTaskId: null,
    title: "운영 Runbook 재정비",
    description: "장애 대응 절차와 책임 체계를 문서화합니다.",
    assignee: "강유리",
    assigneeId: "user-member-2",
    priority: "medium",
    status: "on_hold",
    isCompleted: false,
    startDate: "2026-04-02",
    dueDate: "2026-04-15",
    memo: "보안팀 확인 후 공개",
    checklist: [
      { id: "check-runbook-1", text: "장애 단계 분류", isCompleted: true, createdAt: now },
      { id: "check-runbook-2", text: "연락망 업데이트", isCompleted: false, createdAt: now },
    ],
    approval: {
      status: "pending",
      approverId: "user-admin",
      approvedAt: null,
    },
    createdById: "user-member-2",
    updatedById: "user-member-2",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-legacy-close",
    projectId: "project-legacy",
    parentTaskId: null,
    title: "이전 전환 과제 종료 보고",
    description: "완료된 전환 과제 종료 보고서를 정리합니다.",
    assignee: "PMO",
    assigneeId: "user-admin",
    priority: "low",
    status: "done",
    isCompleted: true,
    startDate: "2026-03-01",
    dueDate: "2026-03-07",
    memo: "",
    checklist: [],
    approval: {
      status: "approved",
      approverId: "user-admin",
      approvedAt: now,
    },
    createdById: "user-admin",
    updatedById: "user-admin",
    createdAt: now,
    updatedAt: now,
  },
];

export function getInitialData() {
  return {
    projects: applyProjectProgress(baseProjects, baseTasks),
    tasks: baseTasks,
    selectedProjectId: "project-2026-plan",
    expandedProjectIds: [
      "project-2026-plan",
      "project-product-dev",
      "project-sales-marketing",
      "project-management-support",
    ],
  };
}
